import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const snapshot=JSON.parse(await readFile(new URL('../src/exoplanets.json',import.meta.url),'utf8'));
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const base=process.env.TEST_URL||'http://localhost:5174';
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1,hasTouch:true});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('fonts.googleapis'))errors.push(m.text());});
 await page.goto(base,{waitUntil:'networkidle'});
 await expect(page.locator('#universe')).toBeVisible();await expect(page.locator('.loading')).toBeHidden();
 await expect(page.locator('.webgl-error')).toHaveCount(0);
 await expect(page.locator('[data-scale="0"]')).toHaveAttribute('aria-pressed','true');
 await page.locator('[data-action="rotate"]').click();
 await page.screenshot({path:'test-results/planets-overview.png'});
 await page.locator('[data-action="planets"]').first().click();
 await expect(page.locator('.solar-shortcuts button')).toHaveCount(8);
 await expect(page.locator('#planet-results .planet-result')).toHaveCount(24);
 await expect(page.locator('#planet-count')).toContainText((snapshot.metadata.planetCount+8).toLocaleString('en-US'));
 const first=await page.locator('#planet-results .planet-result').first().getAttribute('data-object');
 await page.locator('[data-catalog-page="next"]').click();
 assert.notEqual(await page.locator('#planet-results .planet-result').first().getAttribute('data-object'),first);
 await page.locator('[data-catalog-filter="solar"]').click();
 await expect(page.locator('#planet-results .planet-result')).toHaveCount(8);
 await page.locator('[data-catalog-filter="exoplanet"]').click();
 await expect(page.locator('#planet-count')).toContainText(snapshot.metadata.planetCount.toLocaleString('en-US'));
 await page.locator('#planet-search').fill('TRAPPIST-1');
 await expect(page.locator('#planet-results .planet-result')).toHaveCount(7);
 await page.screenshot({path:'test-results/planet-catalog.png'});
 await page.locator('#planet-results [data-object="exo-TRAPPIST-1%20e"]').click();
 await expect(page.locator('#modal')).not.toBeVisible();
 await expect(page.locator('#object-card h2')).toHaveText('TRAPPIST-1 e');
 await expect(page.locator('#scale-title')).toContainText('TRAPPIST-1');
 await expect(page.locator('#object-card')).toContainText('Illustrative appearance');
 await page.waitForTimeout(1900);
 await page.screenshot({path:'test-results/exoplanet-close.png'});
 await page.locator('[data-action="planets"]').first().click();
 await page.locator('.solar-shortcuts [data-object="earth"]').click();
 await expect(page.locator('#object-card h2')).toHaveText('Earth');
 await page.waitForTimeout(1900);
 await page.screenshot({path:'test-results/earth-close.png'});
 await page.locator('[data-scale="0"]').click();
 await expect(page.locator('#object-card h2')).toHaveText('Earth');
 await page.locator('.immersion-button').click();
 await expect(page.locator('.app-shell')).toHaveClass(/cinematic/,{timeout:6500});
 await page.waitForTimeout(1900);
 await expect(page.locator('#map-labels')).toBeHidden();
 assert.equal((await page.locator('body').innerText()).trim(),'','immersive view contains no overlay writing');
 await page.screenshot({path:'test-results/earth-immersive.png'});
 await page.keyboard.press('Escape');
 await expect(page.locator('.app-shell')).not.toHaveClass(/cinematic/);
 await page.locator('[data-action="zoom-in"]').click();
 await page.locator('[data-action="zoom-out"]').click();
 for(let i=1;i<5;i++){
  await page.locator(`[data-scale="${i}"]`).click();
  await expect(page.locator(`[data-scale="${i}"]`)).toHaveAttribute('aria-pressed','true');
  await page.waitForTimeout(1600);
 }
 await page.locator('[data-action="search"]').click();
 await page.locator('#search-input').fill('Wolf 359');
 await page.locator('.search-result').click();
 await expect(page.locator('#object-card h2')).toHaveText('Wolf 359');
 const missing=snapshot.planets.find(p=>p.distancePc===null);
 await page.locator('[data-action="search"]').click();
 await page.locator('#search-input').fill(missing.name);
 await page.locator(`.search-result[data-object="${missing.id}"]`).click();
 await expect(page.locator('#object-card h2')).toHaveText(missing.name);
 await expect(page.locator('#object-card')).toContainText('unknown');
 await page.locator('[data-action="settings"]').click();
 await page.locator('[data-quality="low"]').click();
 await expect(page.locator('[data-quality="low"]')).toHaveAttribute('aria-pressed','true');
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-action="planets"]').first().click();
 await page.locator('.solar-shortcuts [data-object="saturn"]').click();
 await page.waitForTimeout(1900);
 await page.locator('.view-controls [data-action="object"]').click();
 await expect(page.locator('#modal-body h2')).toHaveText('Saturn');
 await page.keyboard.press('Escape');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'test-results/mobile-saturn.png'});
 await page.locator('.immersion-button').click();
 await expect(page.locator('.app-shell')).toHaveClass(/cinematic/,{timeout:6500});
 await page.waitForTimeout(1900);
 assert.equal((await page.locator('body').innerText()).trim(),'');
 await page.screenshot({path:'test-results/mobile-immersive.png'});
 await page.touchscreen.tap(190,280);
 await page.locator('.exit-cinema').click();
 await expect(page.locator('.app-shell')).not.toHaveClass(/cinematic/);
 await page.locator('[data-action="vr"]').first().click();
 await expect(page.locator('#xr-status')).not.toBeEmpty();
 await expect(page.locator('[data-action="start-vr"]')).toBeDisabled();
 await page.keyboard.press('Escape');
 await page.locator('[data-action="tour"]').click();
 await expect(page.locator('[data-action="tour"]')).toHaveAttribute('aria-pressed','true');
 await page.locator('[data-action="tour"]').click();
 assert.deepEqual(errors,[],'no runtime or shader errors');
 console.log('PASS: solar default, full NASA catalog counts/pagination/host search, planet focus, missing measurements, unobstructed immersion, mobile touch restore, five scales, VR fallback and tour.');
 console.log('Screenshots saved in test-results/ including earth-immersive.png and mobile-saturn.png.');
} finally {await browser.close();}
