import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try {
 const page=await browser.newPage({viewport:{width:1280,height:800},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto((process.env.ENGINE_TEST_URL||'http://localhost:5173')+'/tests/fixtures/engine.html',{waitUntil:'networkidle'});
 await page.waitForFunction(()=>window.atlas?.ready);
 assert.equal(await page.evaluate(()=>atlas.index),0);
 assert.equal(await page.evaluate(()=>atlas.targets.length),await page.evaluate(()=>catalog.solar.length+solarMoons.length));
 await page.evaluate(()=>atlas.focusObject(catalog.solar.find(p=>p.id==='earth')));
 await page.waitForFunction(()=>!atlas.cameraFlight);
 const focused=await page.evaluate(()=>({radius:atlas.selected.size,distance:atlas.camera.position.distanceTo(atlas.controls.target),minimum:atlas.controls.minDistance,target:atlas.controls.target.toArray(),position:atlas.selected.position}));
 assert.ok(focused.distance<4,'actual camera reached inside the former four-unit floor');
 assert.ok(focused.distance>focused.radius);
 assert.ok(focused.target.every((v,i)=>Math.abs(v-focused.position[i])<1e-8));
 await page.evaluate(()=>atlas.zoom(.01));
 await page.waitForFunction(()=>!atlas.cameraFlight);
 assert.ok(await page.evaluate(()=>atlas.camera.position.distanceTo(atlas.controls.target)>atlas.selected.size));
 await page.evaluate(()=>atlas.setImmersive(true));
 assert.equal(await page.evaluate(()=>atlas.selectionRing.visible),false);
 assert.equal(await page.evaluate(()=>atlas.content.getObjectByName('grid').visible),false);
 await expect(page.locator('.labels')).toBeHidden();
 const planet=await page.evaluate(()=>{const p=exoplanets.find(p=>p.name==='TRAPPIST-1 e');atlas.focusObject(p);return p.id;});
 await page.waitForFunction(()=>!atlas.cameraFlight);
 assert.deepEqual(await page.evaluate(()=>[atlas.index,atlas.systemHost,atlas.objects.length,atlas.selected.id]),[5,'TRAPPIST-1',8,planet]);
 assert.equal(await page.evaluate(()=>atlas.content.getObjectByName('orbits').visible),false);
 await page.evaluate(()=>atlas.setImmersive(false));
 assert.equal(await page.evaluate(()=>atlas.selectionRing.visible),true);
 await page.evaluate(()=>{const p=exoplanets.find(p=>p.distancePc===null);atlas.focusObject(p);});
 await page.waitForFunction(()=>!atlas.cameraFlight);
 assert.ok(await page.evaluate(()=>atlas.camera.position.toArray().every(Number.isFinite)));
 assert.equal(await page.evaluate(()=>atlas.selected.distancePc),null);
 await page.evaluate(()=>atlas.setScale(1));
 await page.evaluate(()=>atlas.setLayer('particles',false));
 const measured=await page.evaluate(()=>{const points=[];atlas.content.traverse(o=>{if(o.isPoints&&!o.userData.particles)points.push(o.visible);});return points;});
 assert.ok(measured.length&&measured.every(Boolean));
 await page.evaluate(()=>atlas.dispose());
 assert.deepEqual(errors,[]);
 console.log('PASS: real renderer default planets, camera zoom floor, focus target, surface boundary, clean mode, host systems, missing distances, real-star visibility.');
} finally {await browser.close();}
