import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { solarMoons, moonsForPlanet } from '../src/moons.js';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try {
  const page=await browser.newPage({viewport:{width:1440,height:960},locale:'en-US',reducedMotion:'reduce'});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('fonts.googleapis'))errors.push(m.text());});
  await page.goto(process.env.TEST_URL||'http://localhost:5174',{waitUntil:'networkidle'});
  await expect(page.locator('.loading')).toBeHidden();
  await page.locator('[data-action="planets"]').first().click();
  await page.locator('.solar-shortcuts [data-object="earth"]').click();
  await expect(page.locator('#object-card h2')).toHaveText('Earth');
  await expect(page.locator('#object-card [data-action="moons"]')).toContainText('(1)');
  await page.locator('#object-card [data-action="moon-system"]').click();
  await expect(page.locator('#map-labels .map-label').filter({hasText:/^Moon$/})).toBeVisible();
  await page.screenshot({path:'test-results/moons-earth-system.png'});
  await page.locator('#object-card [data-action="moons"]').click();
  await expect(page.locator('#moon-parent')).toHaveValue('earth');
  await expect(page.locator('#planet-results .planet-result')).toHaveCount(1);
  await page.locator('#planet-results [data-object="moon"]').click();
  await expect(page.locator('#object-card h2')).toHaveText('Moon');
  await expect(page.locator('#object-card')).toContainText('384,400');
  await expect(page.locator('#object-card')).toContainText('1,737.4');
  await expect(page.locator('#object-card [data-action="focus"]')).toHaveText('Inspect moon');
  await expect(page.locator('.planet-art,.galaxy-art,.planet-preview,.compass')).toHaveCount(0);
  await page.screenshot({path:'test-results/moon-inspect.png'});
  await page.locator('#object-card [data-object="earth"]').click();
  await expect(page.locator('#object-card h2')).toHaveText('Earth');
  await page.locator('[data-action="planets"]').first().click();
  await page.locator('[data-catalog-filter="moon"]').click();
  await page.locator('#moon-parent').selectOption('');
  await expect(page.locator('#planet-count')).toContainText(String(solarMoons.length));
  await expect(page.locator('#planet-results .planet-result')).toHaveCount(24);
  await page.locator('[data-catalog-page="next"]').click();
  await expect(page.locator('#planet-results .planet-result')).toHaveCount(solarMoons.length-24);
  await page.locator('#moon-parent').selectOption('saturn');
  await expect(page.locator('#planet-results .planet-result')).toHaveCount(moonsForPlanet('saturn').length);
  const source=await page.locator('.catalog-provenance a').last().getAttribute('href');
  assert.match(source,/^https:\/\/ssd\.jpl\.nasa\.gov\//);
  await page.keyboard.press('Escape');
  await page.locator('[data-scale="1"]').click();
  await page.locator('[data-action="search"]').click();
  await page.locator('#search-input').fill('Luna');
  await page.locator('.search-result[data-object="moon"]').click();
  await expect(page.locator('#object-card h2')).toHaveText('Moon');
  await expect(page.locator('[data-scale="0"]')).toHaveAttribute('aria-pressed','true');
  await page.locator('[data-action="settings"]').click();
  await page.locator('#language-setting').selectOption('it');
  await page.waitForLoadState('networkidle');
  await expect(page.locator('.loading')).toBeHidden();
  await expect(page.locator('html')).toHaveAttribute('lang','it');
  await expect(page.locator('#object-card h2')).toHaveText('Luna');
  await expect(page.locator('#object-card')).toContainText('Terra');
  await expect(page.locator('#object-card [data-action="focus"]')).toHaveText('Osserva il satellite');
  await page.locator('[data-action="settings"]').click();
  await page.locator('#language-setting').selectOption('en');
  await page.waitForLoadState('networkidle');
  await expect(page.locator('.loading')).toBeHidden();
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-action="planets"]').first().click();
  await page.locator('[data-catalog-filter="moon"]').click();
  await page.locator('#moon-parent').selectOption('mars');
  await expect(page.locator('#planet-results .planet-result')).toHaveCount(2);
  await page.screenshot({path:'test-results/moons-mobile-catalogue.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#planet-results [data-object="phobos"]').click();
  await page.locator('.mobile-info').click();
  await expect(page.locator('#modal-body h2')).toHaveText('Phobos');
  await expect(page.locator('#modal-body')).toContainText('Mars');
  await page.keyboard.press('Escape');
  await page.locator('.immersion-button').click();
  await expect(page.locator('.app-shell')).toHaveClass(/cinematic/);
  assert.equal((await page.locator('body').innerText()).trim(),'');
  await page.keyboard.press('Escape');
  assert.deepEqual(errors,[]);
  console.log('PASS: Earth-Moon discovery, moon catalogue filters/pagination, parent navigation, cross-scale alias search, English/Italian view restoration, mobile selection and immersion.');
} finally {await browser.close();}
